// <auto-generated />
using System;
using EFInheritanceDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFInheritanceDemo.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220928150306_BlogAdded")]
    partial class BlogAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFInheritanceDemo.Models.BlogBase", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"), 1L, 1);

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("EFInheritanceDemo.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("EFInheritanceDemo.Models.Blog", b =>
                {
                    b.HasBaseType("EFInheritanceDemo.Models.BlogBase");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BlogURL");

                    b.ToTable("SampleBlogs", (string)null);
                });

            modelBuilder.Entity("EFInheritanceDemo.Models.RssBlog", b =>
                {
                    b.HasBaseType("EFInheritanceDemo.Models.BlogBase");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RssURL");

                    b.ToTable("RssBlogs", (string)null);
                });

            modelBuilder.Entity("EFInheritanceDemo.Models.Student", b =>
                {
                    b.HasBaseType("EFInheritanceDemo.Models.Person");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("EFInheritanceDemo.Models.Teacher", b =>
                {
                    b.HasBaseType("EFInheritanceDemo.Models.Person");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("EFInheritanceDemo.Models.Blog", b =>
                {
                    b.HasOne("EFInheritanceDemo.Models.BlogBase", null)
                        .WithOne()
                        .HasForeignKey("EFInheritanceDemo.Models.Blog", "BlogId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFInheritanceDemo.Models.RssBlog", b =>
                {
                    b.HasOne("EFInheritanceDemo.Models.BlogBase", null)
                        .WithOne()
                        .HasForeignKey("EFInheritanceDemo.Models.RssBlog", "BlogId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
